[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
autonomous_mm = "DxRXCM3egzfmcgBXYAt19xUewgnmrZ575XMwUQr8xQCG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/autonomous-mm/Cargo.toml"
build = "cargo-build-sbf --arch v3"
