[package]
name = "autonomous-mm"
version = "0.1.0"
description = "Market maker autonomo minimale su curva quadratica"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "autonomous_mm"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"

[dev-dependencies]
proptest = "1.11.0"
